version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "express"
      - dependency-name: "eslint"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "sdk-node"  
    ignore:
      - dependency-name: "express"
      - dependency-name: "eslint"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "otelcol-auto-instrumentation"  
    ignore:
      - dependency-name: "express"
      - dependency-name: "eslint"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "add-otelcol"  
    ignore:
      - dependency-name: "express"
      - dependency-name: "eslint"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "meta-package"  
    ignore:
      - dependency-name: "express"
      - dependency-name: "eslint"
